Update check-unused-imports.yml

diff --git a/.github/workflows/check-unused-imports.yml b/.github/workflows/check-unused-imports.yml
--- a/.github/workflows/check-unused-imports.yml
+++ b/.github/workflows/check-unused-imports.yml
@@ -1,34 +1,45 @@
-name: Check for unused imports using Pylint
-
+name: Check for unused imports using Pylint 
 on:
   workflow_call:
-    inputs:
-      languages:
-        description: "Optional input to set languages for unused imports check. Supported values are: 'cpp', 'csharp', 'go', 'java', 'javascript', 'typescript', 'python', 'ruby'. To set multiple languages, use the same syntax as you can see in the default value."
-        required: false
-        type: string
-        default: "['python']"
-
 jobs:
   check-unused-imports:
     runs-on: ubuntu-latest
-    permissions:
-      actions: read
-      contents: read
-
     steps:
       - uses: actions/checkout@v3
-
       - name: Set up Python
         uses: actions/setup-python@v3
         with:
-          python-version: 3.12
-
+          python-version: 3.11
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install pylint
-
       - name: Analysing the code with pylint
         run: | 
-          make unused-imports
+          pylint_files=$(git ls-files *.py src/migration-scripts)
+          set +e
+          output=$(pylint --disable=all --enable=W0611 --output-format=json $pylint_files 2>&1)
+          exit_code=$?
+          set -e
+          if [[ $exit_code -eq 0 ]]; then
+            echo "error_message=No issues in unused-imports" >> $GITHUB_ENV
+            echo "No issues in unused-imports"
+          else
+            # Use jq to parse and format the JSON output for better readability
+            formatted_output=$(echo "$output" | jq -r '.[] | "\(.type): \(.message) in \(.path):\(.line)"')
+            echo "$formatted_output"
+            # Replace newlines with dots for the environment variable
+            formatted_env_output=$(echo "$formatted_output" | tr '\n' '. ')
+            echo "error_message=${formatted_env_output}" >> $GITHUB_ENV
+            exit 1
+          fi
+           
+      - name: Add PR comment
+        if: always()
+        uses: mshick/add-pr-comment@v2
+        with:
+          message: |-
+            ${{ env.error_message == 'No issues in unused-imports' && '👍' || '❌' }}
+            ${{ env.error_message }}
+          message-id: "UNUSED IMPORTS USING PYLINT"
+          allow-repeats: false
