Update codeowners-pr.yml

diff --git a/.github/workflows/codeowners-pr.yml b/.github/workflows/codeowners-pr.yml
--- a/.github/workflows/codeowners-pr.yml
+++ b/.github/workflows/codeowners-pr.yml
@@ -16,19 +16,17 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Check for CODEOWNERS file
-        id: check_codeowners
+      - name: Check and Comment on CODEOWNERS file
         run: |
-          if [ -f "CODEOWNERS" ]; then
-            echo "CODEOWNERS_EXISTS=true" >> $GITHUB_ENV
+          if [ -f "./.github/CODEOWNERS" ]; then
+            CODEOWNERS_EXISTS=true
+            COMMENT_BODY="✅ CODEOWNERS file exists."
           else
-            echo "CODEOWNERS_EXISTS=false" >> $GITHUB_ENV
+            CODEOWNERS_EXISTS=false
+            COMMENT_BODY="❌ No CODEOWNERS file found."
+            echo "No CODEOWNERS file found, failing the check."
+            exit 1
           fi
-
-      - name: Post PR comment
-        if: github.event_name == 'pull_request'
-        run: |
-          COMMENT_BODY="${{ env.CODEOWNERS_EXISTS == 'true' && '✅ CODEOWNERS file exists.' || '❌ No CODEOWNERS file found.' }}"
           PR_COMMENTS_URL=$(jq -r .pull_request.comments_url "$GITHUB_EVENT_PATH")
           curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: application/json" \
